### ISSUE TITLE
intl_utils 1.6.1 depends on petitparser >=1.1.3 <3.0.0

### ISSUE THREAD

**Issue by slavap** [localizely/intl_utils#1]
Please upgrade to petitparser 3+, because I have dependencies conflict with other packages.
For example: flutter_svg
It is especially important for beta, dev, and master channels.

**Comment by aleksakrstic** [comment]
Hi @slavap 
Could you try with global installation of `intl_utils` instead of via `dev_dependencies`, as a temporary solution till update is released?

For instance, activate it globally and then run the generator:

    flutter pub global activate intl_utils 1.6.1
    flutter pub global run intl_utils:generate

That way it should not create a conflict around `petitparser` version.

**Comment by guness** [comment]
this is now becoming a blocker as flutter 1.2.0 is released and the library is incompatible with meta.

**Comment by lzoran** [comment]
Hi @guness,

Thanks for reporting that the Flutter 1.20.0 (stable channel) is now released.
We will update `petitparser` dependency in one of the upcoming releases as `flutter_test` does not depend anymore on it.

Could you give us more details regarding incompatibility with `meta` package?

**Comment by guness** [comment]
Hey sorry, I think I have misread the error logs (still getting used to it). I was confused because it mentioned `flutter_test` at a line and `intl_utils` on previous log.

this is the error I am getting:

> Because every version of flutter_test from sdk depends on meta 1.1.8 and appoint depends on meta ^1.2.0, flutter_test from sdk is forbidden.
> So, because appoint depends on flutter_test any from sdk, version solving failed.
> 
and this was the previous error before I edit some versions:

> Because every version of intl_utils depends on petitparser >=1.1.3 <3.0.0 and xml >=3.7.0 depends on petitparser ^3.0.0, intl_utils is incompatible with xml >=3.7.0.
> And because flutter_svg 0.18.0 depends on xml ^4.1.0 and no versions of flutter_svg match >0.18.0 <0.19.0, intl_utils is incompatible with flutter_svg ^0.18.0.
> So, because appoint depends on both flutter_svg ^0.18.0 and intl_utils ^1.6.2, version solving failed.
> R

**Comment by lzoran** [comment]
Hi @guness,

No problem.
Thanks for the logs, it will help us to better understand potential issues.

**Comment by aleksakrstic** [comment]
New version `1.6.3` supports petitparser `^3.0.0`.

**Comment by rauttech** [comment]
Because every version of flutter_test from sdk depends on petitparser 2.4.0 and intl_utils >=1.7.0 depends on petitparser ^3.1.0, flutter_test from sdk is incompatible with intl_utils >=1.7.0.
So, because markets_owner depends on both intl_utils 1.8.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because markets_owner depends on both intl_utils 1.8.0 and flutter_test any from sdk, version solving failed.)
getig this error please help

**Comment by lzoran** [comment]
Hi @rauttech,

According to the message, you should be able to solve this issue by upgrading the `flutter` to the `>=1.20.0` version or by downgrading the `intl_utils` package to the `1.6.2`.

Hope it helps!

**Comment by rauttech** [comment]
i tried both above solution but not working 
now i get below logs
The current Flutter SDK version is 1.20.0.

Because markets depends on google_maps_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.
pub get failed (1; Because markets depends on google_maps_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.)

**Comment by lzoran** [comment]
Hi @rauttech,

> Because markets depends on google_maps_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.
pub get failed (1; Because markets depends on google_maps_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.)

> Because google_map_location_picker >=3.3.1 depends on intl >=0.16.0 <=0.16.
1 and every version of flutter_localizations from sdk depends on intl 0.17.
0-nullsafety.2, google_map_location_picker >=3.3.1 is incompatible with flu
tter_localizations from sdk.

Maybe I'm missing something, but in the latest error messages, I don't see anything related to the `intl_utils` package. 😕 

Also, I noticed that you are using `intl_utils` as a dependency and that you have the `flutter_intl` config within your `pubspec.yaml` file (enabled "Flutter Intl" IDE plugin).
Out of curiosity, for what you are using the `intl_utils` package in your flutter project? 
Note that enabled "Flutter Intl" IDE plugin will install globally `intl_utils` package for you and use it.
