### ISSUE TITLE
Dependencies are broken on flutter dev channel

### ISSUE THREAD

**Issue by cbenhagen** [localizely/intl_utils#21]
```Because no versions of intl_utils match >1.9.0 <2.0.0 and intl_utils 1.9.0 depends on archive ^2.0.13, intl_utils ^1.9.0 requires archive ^2.0.13.
And because every version of flutter_driver from sdk depends on archive 3.0.0, intl_utils ^1.9.0 is incompatible with flutter_driver from sdk.
So, because my_app depends on both flutter_driver any from sdk and intl_utils ^1.9.0, version solving failed.
pub get failed (1; So, because my_app depends on both flutter_driver any from sdk and intl_utils ^1.9.0, version solving failed.)
```

**Comment by lzoran** [comment]
Hi @cbenhagen,

Thanks for reporting this!

Maybe I'm missing something, but it seems that this issue is related to the null-safety migration.
The `intl_utils` package does not support null-safety at the moment (#14), therefore it will not work on the latest `dev` channels.

**Comment by cbenhagen** [comment]
You can use nullsafe libraries without opting into nullsafety. Just like package:flutter is null safe on the dev channel, even if your app is not.

**Comment by lzoran** [comment]
Hi @cbenhagen,

Sorry for the late response.

If we update `archive` dependency to the `^3.0.0` version, then `intl_utils` package can't be used on the current `stable` channel (min sdk constraint issue - _"The current Dart SDK version is 2.10.5. Because flutter_app depends on archive >=3.0.0-nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed."_). 

The second problem is that other `intl_utils` dependencies will have a conflict with the dependencies of the updated `archive` package, and we can't migrate them all at the moment 😞.

**Comment by cbenhagen** [comment]
So what is the plan? There will be a new stable and beta release tomorrow. Will you support it? Is there a plan to support the dev channel in the near future?

**Comment by cbenhagen** [comment]
Our app is being released on macOS, so we need to support the dev (and after tomorrow's announcement the beta) channel.

**Comment by lzoran** [comment]
Hi @cbenhagen,

The `intl_utils 2.0.0` package is released now. It uses null-safety and works with Flutter 2.0.
Regarding the `flutter_driver` dependency conflict, I believe that it should work well now on the `dev` channel.
