### ISSUE TITLE
Difference between `current` and `of()`

### ISSUE THREAD

**Issue by danielgomezrico** [localizely/intl_utils#28]
Hi

I can access the class by using the static variable `current` or by the static function `of(context)`

An example of my generated class is:

```dart

class I18n {
  I18n();
  
  static I18n current;
  
  static I18n of(BuildContext context) {
    return Localizations.of<I18n>(context, I18n);
  }
```

What's the difference between each way?
What will be the consequence of using `current` everywhere?

**Comment by EdwynZNGR** [comment]
`.of(context)` makes use of the inheritance (Inhereted widget) to update your widgets accordingly when there is a change in the localizations of your device, current won't trigger an update, useful for example when sending some text that won't require to change (Toast, Snackbar?)

**Comment by danielgomezrico** [comment]
Oh so you mean like an update in real time?

**Comment by EdwynZNGR** [comment]
Basically yes, when an inhereted widget changes it notifies all the widgets in the widgets tree that uses it to update with the new value.

Current is as a singleton instance, it will update in real time but the code that uses it won't re run so its better to use it in other part of your app that you don't want to or won't trigger (sending a message or notification and you don't need to delete the previous just because it's in the previous language)
