### ISSUE TITLE
Problems generating messages when main language has no translation

### ISSUE THREAD

**Issue by chrisDK1977** [localizely/intl_utils#65]
We have arb files for "en" and "de" in a core module.
 
In our main app we override some of the translations in "intl_de.arb" but not in "intl_en.arb". 

The translations we only only overrided in "intl_de.arb" are not generated in the resulting messages_*.dart files.

Is there a way to solve this without copying the original "en" resources also to the main apps arb - files?

**Comment by lzoran** [comment]
Hi @chrisDK1977,

Not sure if I understood the problem best. 😕

Updating translations in non-main arb files (e.g. `intl_de.arb`) should result with updated `messages_*.dart` files (e.g. `messages_de.arb`). As I can see, this works well.

In case you have a modular project structure, could you check if running `flutter pub run intl_utils:generate` from the root of the module helps?

Also, keep in mind that there are some known limitations regarding the localization of the modular Flutter apps ([issue](https://github.com/localizely/flutter-intl-intellij/issues/22)).

A minimal reproducible example is welcome so that we can better understand the issue.

**Comment by chrisDK1977** [comment]
Hi lzoran,

sorry, our key problem is when we have  "intl_de.arb" and "intl_en.arb" and in "intl_de.arb" is a key which is not present ind the "intl_en.arb" it does not get generated to the "messages_de.dart".

If we add that key also to "intl_en.arb" it will be generated but we have some cases we do not want to have it in "intl_en.arb"

**Comment by lzoran** [comment]
Currently, generation relies only on the main language of the project (default is `en`). 
Does setting of the `main_locale` works for you?

The `pubspec.yaml` file:
```
flutter_intl:
  enabled: true
  main_locale: de # This way, you will have access to all messages defined in the 'intl_de.arb' file.
```

**Comment by chrisDK1977** [comment]
Hi lzoran,

in our current case, yes. But it is also possible that some time we want to override "a" only in englisch and "b" only in german...

**Comment by aleksakrstic** [comment]
Hi @chrisDK1977 
Having multiple sources of truths for string keys would create additional issues.

I suggest to define such string keys always for the main language, at least as the empty strings
