### ISSUE TITLE
Analyzer 3.x support

### ISSUE THREAD

**Issue by proninyaroslav** [localizely/intl_utils#73]

**Comment by pavlouha** [comment]
`Because freezed >=1.1.1 depends on analyzer ^3.0.0 and intl_utils >=2.4.1 depends on analyzer ^2.0.0, freezed >=1.1.1 is incompatible with intl_utils >=2.4.1.
So, because yangi_bank depends on both intl_utils >=2.6.0 and freezed >=1.1.1, version solving failed.
pub get failed (1; So, because yangi_bank depends on both intl_utils >=2.6.0 and freezed >=1.1.1, version solving failed.)`

**Comment by lzoran** [comment]
Hi @proninyaroslav, @pavlouha,

Thanks for reporting this!

The `intl_utils 2.6.1` now supports `analyzer ^3.0.0`.
